<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Dashboard extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->auth->is_logged_in();
    }

    public function index()
    {
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main', $data);
    }
}
