<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Dashboard extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->auth->is_logged_in();
        $this->load->model('Home_model');
        
    }

    public function index()
    {
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main', $data);
    }
    public function getdata()
    {
        $data = $this->Home_model->datagrafik();
        echo json_encode($data);
    }
}
