<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pejabat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pejabat_model');
    } 

    /*
     * Listing of pejabat
     */
    function index()
    {
        $data['pejabat'] = $this->Pejabat_model->get_all_pejabat();
        
        $data['_view'] = 'pejabat/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pejabat
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idstruktural' => $this->input->post('idstruktural'),
				'status' => $this->input->post('status'),
				'idpegawai' => $this->input->post('idpegawai'),
            );
            
            $pejabat_id = $this->Pejabat_model->add_pejabat($params);
            redirect('pejabat/index');
        }
        else
        {            
            $data['_view'] = 'pejabat/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pejabat
     */
    function edit($idpejabat)
    {   
        // check if the pejabat exists before trying to edit it
        $data['pejabat'] = $this->Pejabat_model->get_pejabat($idpejabat);
        
        if(isset($data['pejabat']['idpejabat']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idstruktural' => $this->input->post('idstruktural'),
					'status' => $this->input->post('status'),
					'idpegawai' => $this->input->post('idpegawai'),
                );

                $this->Pejabat_model->update_pejabat($idpejabat,$params);            
                redirect('pejabat/index');
            }
            else
            {
                $data['_view'] = 'pejabat/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pejabat you are trying to edit does not exist.');
    } 

    /*
     * Deleting pejabat
     */
    function remove($idpejabat)
    {
        $pejabat = $this->Pejabat_model->get_pejabat($idpejabat);

        // check if the pejabat exists before trying to delete it
        if(isset($pejabat['idpejabat']))
        {
            $this->Pejabat_model->delete_pejabat($idpejabat);
            redirect('pejabat/index');
        }
        else
            show_error('The pejabat you are trying to delete does not exist.');
    }
    
}
