<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Suratmasuk extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Suratmasuk_model');
    } 

    /*
     * Listing of suratmasuk
     */
    function index()
    {
        $data['suratmasuk'] = $this->Suratmasuk_model->get_all_suratmasuk();
        
        $data['_view'] = 'suratmasuk/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new suratmasuk
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nomor_surat' => $this->input->post('nomor_surat'),
				'lampiran' => $this->input->post('lampiran'),
				'tujuan' => $this->input->post('tujuan'),
				'pengirim' => $this->input->post('pengirim'),
				'tg_surat' => $this->input->post('tg_surat'),
				'berkas' => $this->input->post('berkas'),
				'idkategori_surat' => $this->input->post('idkategori_surat'),
				'idpejabat' => $this->input->post('idpejabat'),
				'status' => $this->input->post('status'),
            );
            
            $suratmasuk_id = $this->Suratmasuk_model->add_suratmasuk($params);
            redirect('suratmasuk/index');
        }
        else
        {            
            $data['_view'] = 'suratmasuk/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a suratmasuk
     */
    function edit($idarsip_surat)
    {   
        // check if the suratmasuk exists before trying to edit it
        $data['suratmasuk'] = $this->Suratmasuk_model->get_suratmasuk($idarsip_surat);
        
        if(isset($data['suratmasuk']['idarsip_surat']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nomor_surat' => $this->input->post('nomor_surat'),
					'lampiran' => $this->input->post('lampiran'),
					'tujuan' => $this->input->post('tujuan'),
					'pengirim' => $this->input->post('pengirim'),
					'tg_surat' => $this->input->post('tg_surat'),
					'berkas' => $this->input->post('berkas'),
					'idkategori_surat' => $this->input->post('idkategori_surat'),
					'idpejabat' => $this->input->post('idpejabat'),
					'status' => $this->input->post('status'),
                );

                $this->Suratmasuk_model->update_suratmasuk($idarsip_surat,$params);            
                redirect('suratmasuk/index');
            }
            else
            {
                $data['_view'] = 'suratmasuk/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The suratmasuk you are trying to edit does not exist.');
    } 

    /*
     * Deleting suratmasuk
     */
    function remove($idarsip_surat)
    {
        $suratmasuk = $this->Suratmasuk_model->get_suratmasuk($idarsip_surat);

        // check if the suratmasuk exists before trying to delete it
        if(isset($suratmasuk['idarsip_surat']))
        {
            $this->Suratmasuk_model->delete_suratmasuk($idarsip_surat);
            redirect('suratmasuk/index');
        }
        else
            show_error('The suratmasuk you are trying to delete does not exist.');
    }
    
}
