<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kategorisurat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kategorisurat by idkategori_surat
     */
    function get_kategorisurat($idkriteria)
    {
        return $this->db->query("SELECT
            `kategorisurat`.*,
            `kriteria`.`kriteria`
        FROM
            `kategorisurat`
            LEFT JOIN `kriteria` ON `kategorisurat`.`idkriteria` = `kriteria`.`idkriteria`
        WHERE `kriteria`.`idkriteria`='$idkriteria'")->result_array();
    }
        
    /*
     * Get all kategorisurat
     */
    function get_all_kategorisurat()
    {
        $this->db->order_by('idkategori_surat', 'desc');
        return $this->db->get('kategorisurat')->result_array();
    }
        
    /*
     * function to add new kategorisurat
     */
    function add_kategorisurat($params)
    {
        $this->db->insert('kategorisurat',$params);
        $params['idkategori_surat']= $this->db->insert_id();
        return $params;
    }
    
    /*
     * function to update kategorisurat
     */
    function update_kategorisurat($idkategori_surat,$params)
    {
        $this->db->where('idkategori_surat',$idkategori_surat);
        return $this->db->update('kategorisurat',$params);
    }
    
    /*
     * function to delete kategorisurat
     */
    function delete_kategorisurat($idkategori_surat)
    {
        return $this->db->delete('kategorisurat',array('idkategori_surat'=>$idkategori_surat));
    }
}
