<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kriterium_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kriterium by idkriteria
     */
    function get_kriterium($idkriteria)
    {
        return $this->db->get_where('kriteria',array('idkriteria'=>$idkriteria))->row_array();
    }
        
    /*
     * Get all kriteria
     */
    function get_all_kriteria()
    {
        $this->db->order_by('idkriteria', 'desc');
        return $this->db->get('kriteria')->result_array();
    }
        
    /*
     * function to add new kriterium
     */
    function add_kriterium($params)
    {
        $this->db->insert('kriteria',$params);
        $params['idkriteria'] = $this->db->insert_id();
        return $params;
    }
    
    /*
     * function to update kriterium
     */
    function update_kriterium($idkriteria,$params)
    {
        $this->db->where('idkriteria',$idkriteria);
        return $this->db->update('kriteria',$params);
    }
    
    /*
     * function to delete kriterium
     */
    function delete_kriterium($idkriteria)
    {
        return $this->db->delete('kriteria',array('idkriteria'=>$idkriteria));
    }
}
