<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mahasiswa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get mahasiswa by Id
     */
    function get_mahasiswa($Id)
    {
        return $this->db->get_where('mahasiswa',array('Id'=>$Id))->row_array();
    }
        
    /*
     * Get all mahasiswa
     */
    function get_all_mahasiswa()
    {
        $this->db->order_by('Id', 'desc');
        return $this->db->get('mahasiswa')->result_array();
    }
        
    /*
     * function to add new mahasiswa
     */
    function add_mahasiswa($params)
    {
        $this->db->insert('mahasiswa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update mahasiswa
     */
    function update_mahasiswa($Id,$params)
    {
        $this->db->where('Id',$Id);
        return $this->db->update('mahasiswa',$params);
    }
    
    /*
     * function to delete mahasiswa
     */
    function delete_mahasiswa($Id)
    {
        return $this->db->delete('mahasiswa',array('Id'=>$Id));
    }
}
