<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pejabat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pejabat by idpejabat
     */
    function get_pejabat($idpejabat)
    {
        return $this->db->get_where('pejabat',array('idpejabat'=>$idpejabat))->row_array();
    }
        
    /*
     * Get all pejabat
     */
    function get_all_pejabat()
    {
        $result = $this->db->query("SELECT
            `pejabat`.*,
            `struktural`.`nm_struktural`,
            `pegawai`.`Nama`
        FROM
            `pejabat`
            LEFT JOIN `pegawai` ON `pejabat`.`idpegawai` = `pegawai`.`idpegawai`
            LEFT JOIN `struktural` ON `struktural`.`idstruktural` =
            `pejabat`.`idstruktural`")->result_array();
        return $result;
    }
        
    /*
     * function to add new pejabat
     */
    function add_pejabat($params)
    {
        $this->db->trans_begin();
        $this->db->where('idstruktural',$params['idstruktural']);
        $this->db->update('pejabat', ['status'=>false]); 
        $this->db->insert('pejabat',$params);
        $id = $this->db->insert_id();
        
        if($this->db->trans_status()){
            $this->db->trans_commit();
            $result = $this->db->query("SELECT
                `pejabat`.*,
                `struktural`.`nm_struktural`,
                `pegawai`.`Nama`
            FROM
                `pejabat`
                LEFT JOIN `pegawai` ON `pejabat`.`idpegawai` = `pegawai`.`idpegawai`
                LEFT JOIN `struktural` ON `struktural`.`idstruktural` =
                `pejabat`.`idstruktural`
            WHERE pejabat.idpejabat= '$id'")->row_array();
            return $result;
        }else{
            $this->db->trans_rollback();
            return $this->db->trans_status();
        }
    }
    
    /*
     * function to update pejabat
     */
    function update_pejabat($idpejabat,$params)
    {
        $item = [
            'idstruktural'=>$params['idstruktural'],
            'status'=>$params['status'],
            'NoSK'=>$params['NoSK'],
            'idpegawai'=>$params['idpegawai']
        ];
        $this->db->where('idpejabat',$idpejabat);
        $this->db->update('pejabat',$params);
        $result = $this->db->query("SELECT
            `pejabat`.*,
            `struktural`.`nm_struktural`,
            `pegawai`.`Nama`
        FROM
            `pejabat`
            LEFT JOIN `pegawai` ON `pejabat`.`idpegawai` = `pegawai`.`idpegawai`
            LEFT JOIN `struktural` ON `struktural`.`idstruktural` =
            `pejabat`.`idstruktural`
        WHERE pejabat.idpejabat= '$idpejabat'")->row_array();
        return $result;
    }
    
    /*
     * function to delete pejabat
     */
    function delete_pejabat($idpejabat)
    {
        return $this->db->delete('pejabat',array('idpejabat'=>$idpejabat));
    }
}
