<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Suratmasuk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get suratmasuk by idarsip_surat
     */
    function get_suratmasuk($idarsip_surat)
    {
        return $this->db->get_where('suratmasuk',array('idarsip_surat'=>$idarsip_surat))->row_array();
    }
        
    /*
     * Get all suratmasuk
     */
    function get_all_suratmasuk()
    {
        $this->db->order_by('idarsip_surat', 'desc');
        return $this->db->get('suratmasuk')->result_array();
    }
        
    /*
     * function to add new suratmasuk
     */
    function add_suratmasuk($params)
    {
        $this->db->insert('suratmasuk',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update suratmasuk
     */
    function update_suratmasuk($idarsip_surat,$params)
    {
        $this->db->where('idarsip_surat',$idarsip_surat);
        return $this->db->update('suratmasuk',$params);
    }
    
    /*
     * function to delete suratmasuk
     */
    function delete_suratmasuk($idarsip_surat)
    {
        return $this->db->delete('suratmasuk',array('idarsip_surat'=>$idarsip_surat));
    }
}
