<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Suratmahasiswa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get suratmahasiswa by idsuratmahasiswa
     */
    function get_suratmahasiswa($idsuratmahasiswa)
    {
        return $this->db->get_where('suratmahasiswa',array('idsuratmahasiswa'=>$idsuratmahasiswa))->row_array();
    }
        
    /*
     * Get all suratmahasiswa
     */
    function get_all_suratmahasiswa()
    {
        $this->db->order_by('idsuratmahasiswa', 'desc');
        return $this->db->get('suratmahasiswa')->result_array();
    }
        
    /*
     * function to add new suratmahasiswa
     */
    function add_suratmahasiswa($params)
    {
        $this->db->insert('suratmahasiswa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update suratmahasiswa
     */
    function update_suratmahasiswa($idsuratmahasiswa,$params)
    {
        $this->db->where('idsuratmahasiswa',$idsuratmahasiswa);
        return $this->db->update('suratmahasiswa',$params);
    }
    
    /*
     * function to delete suratmahasiswa
     */
    function delete_suratmahasiswa($idsuratmahasiswa)
    {
        return $this->db->delete('suratmahasiswa',array('idsuratmahasiswa'=>$idsuratmahasiswa));
    }
}
