<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tembusan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tembusan by idtembusan
     */
    function get_tembusan($idtembusan)
    {
        return $this->db->get_where('tembusan',array('idtembusan'=>$idtembusan))->row_array();
    }
        
    /*
     * Get all tembusan
     */
    function get_all_tembusan()
    {
        $this->db->order_by('idtembusan', 'desc');
        return $this->db->get('tembusan')->result_array();
    }
        
    /*
     * function to add new tembusan
     */
    function add_tembusan($params)
    {
        $this->db->insert('tembusan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tembusan
     */
    function update_tembusan($idtembusan,$params)
    {
        $this->db->where('idtembusan',$idtembusan);
        return $this->db->update('tembusan',$params);
    }
    
    /*
     * function to delete tembusan
     */
    function delete_tembusan($idtembusan)
    {
        return $this->db->delete('tembusan',array('idtembusan'=>$idtembusan));
    }
}
