<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kategorisurat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kategorisurat_model');
    } 

    /*
     * Listing of kategorisurat
     */
    function index($idkriteria=null)
    {
        $data['_view'] = 'kategorisurat/index';
        $this->load->view('layouts/main',$data);
    }

    public function getdata($idkriteria = null)
    {
        $this->load->model('Kriterium_model');
        $data['kriterium'] = $this->Kriterium_model->get_kriterium($idkriteria);
        $data['kategorisurat'] = $this->Kategorisurat_model->get_kategorisurat($idkriteria);
        echo json_encode($data);
    }

    /*
     * Adding a new kategorisurat
     */
    function add()
    {   
        $params = json_decode($this->security->xss_clean($this->input->raw_input_stream), true);
        if(!isset($params['idkategori_surat']))     
        {   
            $result = $this->Kategorisurat_model->add_kategorisurat($params);
            echo json_encode($result);
        }else{
            $this->Kategorisurat_model->update_kategorisurat($params['idkategori_surat'],$params);
            echo json_encode($result);
        }
        
    }  

    /*
     * Editing a kategorisurat
     */
    function edit($idkategori_surat)
    {   
        // check if the kategorisurat exists before trying to edit it
        $data['kategorisurat'] = $this->Kategorisurat_model->get_kategorisurat($idkategori_surat);
        
        if(isset($data['kategorisurat']['idkategori_surat']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama_kategori' => $this->input->post('nama_kategori'),
					'keterangan' => $this->input->post('keterangan'),
					'idkriteria' => $this->input->post('idkriteria'),
                );

                $this->Kategorisurat_model->update_kategorisurat($idkategori_surat,$params);            
                redirect('kategorisurat/index');
            }
            else
            {
                $data['_view'] = 'kategorisurat/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kategorisurat you are trying to edit does not exist.');
    } 

    /*
     * Deleting kategorisurat
     */
    function remove($idkategori_surat)
    {
        $kategorisurat = $this->Kategorisurat_model->get_kategorisurat($idkategori_surat);

        // check if the kategorisurat exists before trying to delete it
        if(isset($idkategori_surat))
        {
            $this->Kategorisurat_model->delete_kategorisurat($idkategori_surat);
            echo json_encode(['message'=>'berhasil']);
        }
        else{
            var_dump(http_response_code(400));
            echo json_encode(['message'=>'tidak ada data']);;
        }
    }
    
}
