<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kategorisurat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kategorisurat_model');
    } 

    /*
     * Listing of kategorisurat
     */
    function index()
    {
        $data['kategorisurat'] = $this->Kategorisurat_model->get_all_kategorisurat();
        
        $data['_view'] = 'kategorisurat/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new kategorisurat
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama_kategori' => $this->input->post('nama_kategori'),
				'keterangan' => $this->input->post('keterangan'),
				'idkriteria' => $this->input->post('idkriteria'),
            );
            
            $kategorisurat_id = $this->Kategorisurat_model->add_kategorisurat($params);
            redirect('kategorisurat/index');
        }
        else
        {            
            $data['_view'] = 'kategorisurat/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kategorisurat
     */
    function edit($idkategori_surat)
    {   
        // check if the kategorisurat exists before trying to edit it
        $data['kategorisurat'] = $this->Kategorisurat_model->get_kategorisurat($idkategori_surat);
        
        if(isset($data['kategorisurat']['idkategori_surat']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama_kategori' => $this->input->post('nama_kategori'),
					'keterangan' => $this->input->post('keterangan'),
					'idkriteria' => $this->input->post('idkriteria'),
                );

                $this->Kategorisurat_model->update_kategorisurat($idkategori_surat,$params);            
                redirect('kategorisurat/index');
            }
            else
            {
                $data['_view'] = 'kategorisurat/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kategorisurat you are trying to edit does not exist.');
    } 

    /*
     * Deleting kategorisurat
     */
    function remove($idkategori_surat)
    {
        $kategorisurat = $this->Kategorisurat_model->get_kategorisurat($idkategori_surat);

        // check if the kategorisurat exists before trying to delete it
        if(isset($kategorisurat['idkategori_surat']))
        {
            $this->Kategorisurat_model->delete_kategorisurat($idkategori_surat);
            redirect('kategorisurat/index');
        }
        else
            show_error('The kategorisurat you are trying to delete does not exist.');
    }
    
}
