<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mahasiswa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mahasiswa_model');
    } 

    /*
     * Listing of mahasiswa
     */
    function index()
    {
        $data['_view'] = 'mahasiswa/index';
        $this->load->view('layouts/main',$data);
    }

    public function getdata()
    {
        $data = $this->Mahasiswa_model->get_all_mahasiswa();
        echo json_encode($data);
    }

    public function getonedata($Id)
    {
        $data = $this->Mahasiswa_model->get_mahasiswa($Id);
        echo json_encode($data);
    }

    public function detail($Id)
    {
        $data['_view'] = 'mahasiswa/edit';
        $this->load->view('layouts/main',$data);
    }
}
