<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Mahasiswa extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('Mahasiswa_model');
        header('Access-Control-Allow-Origin: *');
        header("Access-Control-Allow-Methods: GET, POST, OPTIONS");
    }

    /*
     * Listing of mahasiswa
     */
    public function index()
    {
        $data['_view'] = 'mahasiswa/index';
        $this->load->view('layouts/main', $data);
    }

    public function getdata()
    {
        $data = $this->Mahasiswa_model->get_all_mahasiswa();
        echo json_encode($data);
    }

    public function getonedata($Id)
    {
        $data = $this->Mahasiswa_model->get_mahasiswa($Id);
        echo json_encode($data);
    }

    public function edit($IdUser)
    {
        $params = json_decode($this->security->xss_clean($this->input->raw_input_stream), true);
        $data = $this->Mahasiswa_model->update_mahasiswa($IdUser, $params);
        echo json_encode($data);
    }

    public function detail($Id)
    {
        $data['_view'] = 'mahasiswa/edit';
        $this->load->view('layouts/main', $data);
    }

}
