<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pejabat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pejabat_model');
    } 

    /*
     * Listing of pejabat
     */
    function index()
    {
        $data['_view'] = 'pejabat/index';
        $this->load->view('layouts/main',$data);
    }

    public function getdata()
    {
        $data = $this->Pejabat_model->get_all_pejabat();
        echo json_encode($data);
    }

    function add()
    {   
        $params = json_decode($this->security->xss_clean($this->input->raw_input_stream), true);
        if(!isset($params['idpejabat']))     
        {   
            $result = $this->Pejabat_model->add_pejabat($params);
            echo json_encode($result);
        }else{
            $this->Pejabat_model->update_pejabat($params['idpejabat'],$params);
        }
    }  

    /*
     * Editing a pejabat
     */
    function edit($idpejabat)
    {   
        // check if the pejabat exists before trying to edit it
        $data['pejabat'] = $this->Pejabat_model->get_pejabat($idpejabat);
        
        if(isset($data['pejabat']['idpejabat']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idstruktural' => $this->input->post('idstruktural'),
					'status' => $this->input->post('status'),
					'idpegawai' => $this->input->post('idpegawai'),
                );

                $this->Pejabat_model->update_pejabat($idpejabat,$params);            
                redirect('pejabat/index');
            }
            else
            {
                $data['_view'] = 'pejabat/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pejabat you are trying to edit does not exist.');
    } 

    /*
     * Deleting pejabat
     */
    function remove($idpejabat)
    {
        $pejabat = $this->Pejabat_model->get_pejabat($idpejabat);

        // check if the pejabat exists before trying to delete it
        if(isset($pejabat['idpejabat']))
        {
            $this->Pejabat_model->delete_pejabat($idpejabat);
            redirect('pejabat/index');
        }
        else
            show_error('The pejabat you are trying to delete does not exist.');
    }
    
}
