<?php defined('BASEPATH') OR exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Struktural extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('Struktural_model');
    }

    /*
     * Listing of struktural
     */
    public function index()
    {

        $data['_view'] = 'struktural/index';
        $this->load->view('layouts/main', $data);
    }

    public function getdata()
    {
        $data = $this->Struktural_model->get_all_struktural();
        echo json_encode($data);
    }

    /*
     * Adding a new struktural
     */
    public function add()
    {
        $params = json_decode($this->security->xss_clean($this->input->raw_input_stream), true);
        if(!isset($params['idstruktural']))
            $struktural_id = $this->Struktural_model->add_struktural($params);
        else
            $this->Struktural_model->update_struktural($params['idstruktural'], $params);
        echo json_encode($struktural_id);
    }

    public function edit($idstruktural)
    {
        // check if the struktural exists before trying to edit it
        $data['struktural'] = $this->Struktural_model->get_struktural($idstruktural);

        if (isset($data['struktural']['idstruktural'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'nm_struktural' => $this->input->post('nm_struktural'),
                );

                $this->Struktural_model->update_struktural($idstruktural, $params);
                redirect('struktural/index');
            } else {
                $data['_view'] = 'struktural/edit';
                $this->load->view('layouts/main', $data);
            }
        } else {
            show_error('The struktural you are trying to edit does not exist.');
        }

    }

    /*
     * Deleting struktural
     */
    public function remove($idstruktural)
    {
        $struktural = $this->Struktural_model->get_struktural($idstruktural);

        // check if the struktural exists before trying to delete it
        if (isset($struktural['idstruktural'])) {
            $this->Struktural_model->delete_struktural($idstruktural);
            echo json_encode(['message'=>true]);
        } else {
            echo json_encode(['message'=>false]);
        }

    }

}
