<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Suratinternal extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Suratinternal_model');
    } 

    /*
     * Listing of suratinternal
     */
    function index()
    {
        $data['suratinternal'] = $this->Suratinternal_model->get_all_suratinternal();
        
        $data['_view'] = 'suratinternal/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new suratinternal
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nomor_surat' => $this->input->post('nomor_surat'),
				'lampiran' => $this->input->post('lampiran'),
				'tujuan' => $this->input->post('tujuan'),
				'pengirim' => $this->input->post('pengirim'),
				'tg_surat' => $this->input->post('tg_surat'),
				'berkas' => $this->input->post('berkas'),
				'idkategori_surat' => $this->input->post('idkategori_surat'),
				'status' => $this->input->post('status'),
				'keterangan' => $this->input->post('keterangan'),
            );
            
            $suratinternal_id = $this->Suratinternal_model->add_suratinternal($params);
            redirect('suratinternal/index');
        }
        else
        {            
            $data['_view'] = 'suratinternal/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a suratinternal
     */
    function edit($idarsip_surat)
    {   
        // check if the suratinternal exists before trying to edit it
        $data['suratinternal'] = $this->Suratinternal_model->get_suratinternal($idarsip_surat);
        
        if(isset($data['suratinternal']['idarsip_surat']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nomor_surat' => $this->input->post('nomor_surat'),
					'lampiran' => $this->input->post('lampiran'),
					'tujuan' => $this->input->post('tujuan'),
					'pengirim' => $this->input->post('pengirim'),
					'tg_surat' => $this->input->post('tg_surat'),
					'berkas' => $this->input->post('berkas'),
					'idkategori_surat' => $this->input->post('idkategori_surat'),
					'status' => $this->input->post('status'),
					'keterangan' => $this->input->post('keterangan'),
                );

                $this->Suratinternal_model->update_suratinternal($idarsip_surat,$params);            
                redirect('suratinternal/index');
            }
            else
            {
                $data['_view'] = 'suratinternal/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The suratinternal you are trying to edit does not exist.');
    } 

    /*
     * Deleting suratinternal
     */
    function remove($idarsip_surat)
    {
        $suratinternal = $this->Suratinternal_model->get_suratinternal($idarsip_surat);

        // check if the suratinternal exists before trying to delete it
        if(isset($suratinternal['idarsip_surat']))
        {
            $this->Suratinternal_model->delete_suratinternal($idarsip_surat);
            redirect('suratinternal/index');
        }
        else
            show_error('The suratinternal you are trying to delete does not exist.');
    }
    
}
