<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tembusan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tembusan_model');
    } 

    /*
     * Listing of tembusan
     */
    function index()
    {
        $data['tembusan'] = $this->Tembusan_model->get_all_tembusan();
        
        $data['_view'] = 'tembusan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tembusan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idpejabat' => $this->input->post('idpejabat'),
				'idsuratmahasiswa' => $this->input->post('idsuratmahasiswa'),
            );
            
            $tembusan_id = $this->Tembusan_model->add_tembusan($params);
            redirect('tembusan/index');
        }
        else
        {            
            $data['_view'] = 'tembusan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tembusan
     */
    function edit($idtembusan)
    {   
        // check if the tembusan exists before trying to edit it
        $data['tembusan'] = $this->Tembusan_model->get_tembusan($idtembusan);
        
        if(isset($data['tembusan']['idtembusan']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idpejabat' => $this->input->post('idpejabat'),
					'idsuratmahasiswa' => $this->input->post('idsuratmahasiswa'),
                );

                $this->Tembusan_model->update_tembusan($idtembusan,$params);            
                redirect('tembusan/index');
            }
            else
            {
                $data['_view'] = 'tembusan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tembusan you are trying to edit does not exist.');
    } 

    /*
     * Deleting tembusan
     */
    function remove($idtembusan)
    {
        $tembusan = $this->Tembusan_model->get_tembusan($idtembusan);

        // check if the tembusan exists before trying to delete it
        if(isset($tembusan['idtembusan']))
        {
            $this->Tembusan_model->delete_tembusan($idtembusan);
            redirect('tembusan/index');
        }
        else
            show_error('The tembusan you are trying to delete does not exist.');
    }
    
}
